openapi: 3.0.0
info:
  version: 1.0.0
  title: Wooly API Docs
  description: Wooly API 문서입니다
  license:
    name: MIT
servers:
  - description: dev server
    url: 'https://wooly.co.kr'
paths:
  /app/promise-list:
    get:
      summary: 다짐 목록 API
      tags:
        - promise
      parameters:
        - in: query
          name: date
          required: false
          schema:
            type: string
            example: '2020-12-17'
          description: '조회할 날짜(입력하지 않을 경우, 전체 목록 조회)'
        - in: query
          name: page
          required: false
          schema:
            type: integer
            example: 1
          description: '페이징 인덱스(0이거나 입력하지 않을 경우, 특정 날짜의 전체 목록 조회)'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  isSuccess:
                    type: boolean
                  code:
                    type: integer
                  message:
                    type: string
                  result:
                    type: array
                    items:
                      $ref: '#/components/schemas/Promise'
              example:
                isSuccess: true
                code: 200
                message: 다짐 목록 조회
                result:
                  - profile: ''
                    nickname: 래리
                    promiseIdx: 5
                    createdAt: '2020-11-26T03:15:30.000Z'
                    promise: 힘찬 하루를 보내자
                    public: 1
                  - profile: ''
                    nickname: 래리
                    promiseIdx: 6
                    createdAt: '2020-11-26T03:21:44.000Z'
                    promise: 아자아자
                    public: 0
                  - profile: ''
                    nickname: 래리
                    promiseIdx: 7
                    createdAt: '2020-11-26T04:08:49.000Z'
                    promise: 오늘은 긍정적인 하루를 보내야지
                    public: 1
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalServerError'
        '600':
          $ref: '#/components/responses/DBError'
  /app/promise:
    post:
      summary: 다짐 생성 API
      tags:
        - promise
      parameters:
        - in: header
          name: x-access-token
          type: string
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                promise:
                  type: string
                public:
                  type: string
            example:
              promise: 오늘은 힘찬 하루를 보내야지
              public: ok
      responses:
        '201':
          description: Create Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  isSuccess:
                    type: boolean
                  code:
                    type: integer
                  message:
                    type: string
              example:
                isSuccess: true
                code: 201
                message: 다짐 작성 성공
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalServerError'
        '600':
          $ref: '#/components/responses/DBError'
  /sign-up:
    post:
      summary: 회원가입 API
      tags:
        - user
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
                nickname:
                  type: string
              example:
                email: larry@wooly.co.kr
                password: '1111'
                nickname: 동동이
      responses:
        '200':
          description: SIGN_UP_SUCCESS
          content:
            schema:
              type: object
              properties:
                isSuccess:
                  type: boolean
                code:
                  type: integer
                message:
                  type: string
                result:
                  $ref: '#/components/schemas/Auth'
        '204':
          $ref: '#/components/responses/EmptyValueError'
        '206':
          $ref: '#/components/responses/InvalidValueError'
        '500':
          $ref: '#/components/responses/InternalServerError'
  /sign-in:
    post:
      summary: 로그인 API
      tags:
        - user
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              example:
                email: larry@wooly.co.kr
                password: '1111'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  isSuccess:
                    type: boolean
                  code:
                    type: integer
                  message:
                    type: string
                  result:
                    $ref: '#/components/schemas/Auth'
        '204':
          $ref: '#/components/responses/EmptyValueError'
        '206':
          $ref: '#/components/responses/InvalidValueError'
        '500':
          $ref: '#/components/responses/InternalServerError'
  /kakao:
    post:
      summary: 카카오 로그인 API
      tags:
        - user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                kakaoAccessToken:
                  type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  isSuccess:
                    type: boolean
                  code:
                    type: integer
                  message:
                    type: string
                  result:
                    $ref: '#/components/schemas/Auth'
        '204':
          $ref: '#/components/responses/EmptyValueError'
        '500':
          $ref: '#/components/responses/InternalServerError'
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Promise:
      type: object
      required:
        - promiseIdx
        - promise
        - createdAt
        - public
        - userIdx
      properties:
        promiseIdx:
          type: integer
          description: ObjectID
        promise:
          type: string
        createdAt:
          type: string
        public:
          type: string
        userIdx:
          type: integer
    Auth:
      type: object
      required:
        - token
        - userIdx
        - nickname
        - profile
      properties:
        token:
          type: string
          description: 토큰
        userIdx:
          type: integer
          description: 유저 인덱스
        nickname:
          type: string
          description: 유저 닉네임
        profile:
          type: string
          description: 유저 프로필 사진
    Error:
      type: object
      properties:
        isSuccess:
          type: boolean
        code:
          type: integer
        message:
          type: string
  responses:
    BadRequest:
      description: 잘못된 요청
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            isSuccess: false
            code: 400
            message: 잘못된 요청
    InternalServerError:
      description: 서버 에러
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            isSuccess: false
            code: 500
            message: 서버 내부 오류
    DBError:
      description: 데이터베이스 에러
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            isSuccess: false
            code: 600
            message: 데이터베이스 에러
    EmptyValueError:
      description: 바디값 미입력 오류
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            isSuccess: false
            code: 204
            message: 바디값 미입력 오류
    InvalidValueError:
      description: 유효하지 않은 값
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            isSuccess: false
            code: 206
            message: 유효하지 않은 값
