openapi: "3.0.0"
info:
  version: 1.0.0
  title: Wooly API Docs
  description: Wooly API 문서입니다
  license:
    name: MIT
servers:
  - description: dev server
    url: https://wooly.co.kr
paths:
  $ref: "./paths/_index.yaml"
components:
  # securitySchemes 생략 가능
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Promise:
      type: object
      required:
        - promiseIdx
        - promise
        - createdAt
        - public
        - userIdx
      properties:
        promiseIdx:
          type: integer
          description: ObjectID
        promise:
          type: string
        createdAt:
          type: string
        public:
          type: string
        userIdx:
          type: integer
    Auth:
      type: object
      required:
        - token
        - userIdx
        - nickname
        - profile
      properties:
        token:
          type: string
          description: 토큰
        userIdx:
          type: integer
          description: 유저 인덱스  
        nickname:
          type: string
          description: 유저 닉네임  
        profile:
          type: string
          description: 유저 프로필 사진  
    Error:
      type: object
      properties:
        isSuccess:
          type: boolean
        code:
          type: integer
        message:
          type: string
  responses:
    BadRequest:
      description: 잘못된 요청
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            isSuccess: false
            code: 400
            message: 잘못된 요청
    InternalServerError:
      description: 서버 에러
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            isSuccess: false
            code: 500
            message: 서버 내부 오류
    DBError:
      description: 데이터베이스 에러
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            isSuccess: false
            code: 600
            message: 데이터베이스 에러
    EmptyValueError:
      description: 바디값 미입력 오류
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            isSuccess: false
            code: 204
            message: 바디값 미입력 오류
    InvalidValueError:
      description: 유효하지 않은 값
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            isSuccess: false
            code: 206
            message: 유효하지 않은 값
